release:
  &release 4.15.0

releases:
  - *release
  - 3.10.1
  - 2.4.2

vendor: {
  "css": [
    "https://unpkg.com/font-awesome@4.6.3/css/font-awesome.min.css"
  ],
  "font": [
    "https://unpkg.com/font-awesome@4.6.3/fonts/fontawesome-webfont.woff2?v=4.6.3"
  ],
  "js": [
    "https://unpkg.com/immutable@3.8.1/dist/immutable.min.js",
    "https://unpkg.com/react@15.3.1/dist/react.min.js",
    "https://unpkg.com/react-dom@15.3.1/dist/react-dom.min.js"
  ]
}

sass:
  sass_dir:
    assets/css

exclude:
  - node_modules
  - Gemfile
  - gulpfile.js
  - LICENSE
  - "*.json"
  - "*.log"
  - "*.md"
  - "*.toml"

include:
  - _headers
  - _redirects

incremental: true
