repository: lodash/lodash.com

release:
  &release 4.17.10

releases:
  - *release
  - 3.10.1
  - 2.4.2

brand_color: "#3492ff"
description: A JavaScript utility library delivering consistency, modularity, performance, & extras.

css:
  all:
    - /assets/css/main.css

js:
  docs:
    - /assets/js/docs.js

  home:
    - /assets/js/home.js

links:
  build_differences:
    https://github.com/lodash/lodash/wiki/Build-Differences

  docs_v1:
    https://github.com/lodash/lodash/blob/1.3.1/doc/README.md

  org:
    https://github.com/orgs/lodash

  raw:
    https://raw.githubusercontent.com/lodash/lodash

  repo:
    https://github.com/lodash/lodash

sass:
  sass_dir:
    assets/css

builds:
  *release:
    href: https://cdn.jsdelivr.net/npm/lodash@4.17.10/lodash.min.js
    integrity: sha384-mSSBMtpZHKT74w/c7tDbXmJJtqdlb1lR+PmokfXQwMXWVEWpxD08EA9Ymb+9PpIK

  3.10.1:
    href: https://cdn.jsdelivr.net/lodash/3.10.1/lodash.min.js
    integrity: sha384-0BrUT26SU4JPtbvE/hI6oj4mbEXE32qhRoD51rUTB+QFrg6ViIceJR8op6FmEIA1

  2.4.2:
    href: https://cdn.jsdelivr.net/npm/lodash@2.4.2/dist/lodash.min.js
    integrity: sha384-i14qZ6FYmJXQABb+YG5tH4NXjKOLznxsr5jFsNiJNRcQ77978BoUif762EQyydgt

font-face:
  sourcecodepro:
    light:
      - /assets/fonts/source-code-pro-v7-latin-300.woff2
    semi-bold:
      - /assets/fonts/source-code-pro-v7-latin-600.woff2

vendor:
  js:
    - href: https://embed.runkit.com/
      async: true

    - href: https://cdn.jsdelivr.net/g/fuse@2.6.1,react@15.4.0(react.min.js+react-dom.min.js
      integrity: sha384-txLSiuN1HJSO1or/mE1Y6bvgD0cV3WA6Ss7rs9WqvPQ3zthR8w/DzHpB+DVTDAMz

carbon_ads:
  href: https://cdn.carbonads.com/carbon.js?serve=CKYIEK37&placement=lodashcom
  id: _carbonads_js

google_analytics:
  href: https://www.google-analytics.com/analytics.js
  commands: [['create', 'UA-6065217-64', 'auto'], ['require', 'linkid'], ['send', 'pageview']]

exclude:
  - node_modules
  - tools
  - Gemfile
  - gulpfile.js
  - icons.js
  - LICENSE
  - package.json
  - package-lock.json
  - "*.lock"
  - "*.log"
  - "*.md"
  - "*.toml"

include:
  - _headers
  - _redirects
